-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgUjxOOyWYV2e0kiJX
AMIh5m3hvNS7fkwcwKK9FGWeGTCgCgYIKoZIzj0DAQehRANCAATn4J58ul7C5KOc
bjwCSul0Nt3iLJncfRXOlTKfidoUMvjCLkFLMOhQZWc8UT7NHZ8nefqkjJDCboG4
bHbVywWj
-----END PRIVATE KEY-----